//
//     Generated by class-dump 3.4 (64 bit) (Debug version compiled Oct  5 2013 12:36:13).
//
//     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2012 by Steve Nygard.
//

#import <Foundation/Foundation.h>

@protocol _SBUIWidgetHost <NSObject>
- (void)invalidatePreferredViewSize;
- (void)requestLaunchOfURL:(NSURL *)arg1;
- (void)requestPresentationOfViewController:(NSString *)arg1 presentationStyle:(long long)arg2 context:(NSDictionary *)arg3 completion:(void (^)(void))arg4;
@end

